echo "Commands:"
echo "  $APPNAME update"
echo "     Update the sg-iaas package"
echo "  $APPNAME verify"
echo "     Verify the installation"
echo "  $APPNAME ogw-routes <vpc-id>"
echo "     Check the instance routes set in the vpc"
echo "  $APPNAME help"
echo "     Show this help"